version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - ainpc_prototype_DB__uri=postgresql://postgres:postgres@db:5432/ainpc_prototype
      - ainpc_prototype_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: ainpc_prototype_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/ainpc_prototype_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=ainpc_prototype, ainpc_prototype_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
